apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 343618703554.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 343618703554.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: f46c89c4
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
